# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db4efa45993af81bcb7a75a3c64cd4166c19b9b12cded851d7dd5314a1ba0052f1331e5f3d9683931a4c5a0a19ae3859b61f7830316ee6da7f3d5324a64202f4

test:
  secret_key_base: ac0ce47cdaf25dc82e405ea4dfcb5da6a2dbb7ea823a11c999459a9e33bb87c98cba185b96669bd4f6468a19ec19259fb604a5d1238fc60703db6b92ed985f99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
