# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$(document).ready ->
  $('#books').DataTable({
    "language": {
      "url": "//cdn.datatables.net/plug-ins/1.10.10/i18n/Polish.json"
    }
  })

$(document).ready ->
  $('#author a.add_fields').data('association-insertion-position', 'before').data 'association-insertion-node', 'this'
  $('#author').bind 'cocoon:after-insert', ->
    $('#author_from_list').hide()
    $('#author a.add_fields').hide()
    return
  $('#author').bind 'cocoon:after-remove', ->
    $('#author_from_list').show()
    $('#author a.add_fields').show()
    return
  return

$(document).ready ->
  $('#publishing_house a.add_fields').data('association-insertion-position', 'before').data 'association-insertion-node', 'this'
  $('#publishing_house').bind 'cocoon:after-insert', ->
    $('#publishing_house_from_list').hide()
    $('#publishing_house a.add_fields').hide()
    return
  $('#publishing_house').bind 'cocoon:after-remove', ->
    $('#publishing_house_from_list').show()
    $('#publishing_house a.add_fields').show()
    return
  return

# ---
# generated by js2coffee 2.1.0